# Generated by Django 3.2.5 on 2021-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Goods'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='duration',
        ),
        migrations.AlterField(
            model_name='goods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
