# Generated by Django 3.2.5 on 2021-08-23 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20210820_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AddField(
            model_name='goods',
            name='create_by',
            field=models.ForeignKey(default=1, help_text='创建人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='location',
            field=models.CharField(help_text='填写格式： 二楼-衣柜，方便后期优化', max_length=255, verbose_name='储藏位置'),
        ),
    ]
